@startuml
class Animal {
    - ID: int
    - Species: string
    - Breed: string
    - Age: int
    - Weight: float
    - Description: string
    - Picture
}

class User {
    - Name: string
    - Address: string
    - Email: string
    - YourAdoptionResuests: List<Request>
    + ViewAnimals()
    + AdoptAnimal()
}

class Employee {
    + AddAnimal()
    + ModifyAnimal()
    + ViewRequests()
    + ApproveRequests()
}

class Shelter {
    - AnimalList: List<Animal>
    - EmployeeList: List<Employee>
    - AdoptionList: List<Adoption>
    + AddUser()
    + AddEmployee()
}

class Adoption {
    - UserInfo:
    - AnimalInfo:
    - Status:
}


User <|-- Employee
Shelter o-- Animal
Shelter o-- Employee
Shelter o-- Adoption
Adoption *-- User

@enduml
